name: test-jetstream

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.2 ]
        stack: [ livewire, inertia ]

    name: PHP ${{ matrix.php }} - Stack ${{ matrix.stack }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Setup Laravel
        run: |
          composer create-project laravel/laravel:^10 .
          composer require cbaconnier/laravel-mvc-to-ddd:* --no-interaction --dev
          composer require laravel/jetstream:* --no-interaction

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: 'jetstream'

      - name: Install Jetstream
        run: |
          php artisan jetstream:install ${{ matrix.stack }} --teams --api --verification

      - name: Install NPM dependencies
        run: npm i

      - name: Compile assets
        run: npm run build

      - name: Run Laravel MVC to DDD
        run: |
          php artisan ddd:install

      - name: Execute tests
        run: vendor/bin/phpunit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
